<?php

namespace Fwk\Di;

/**
 * Test class for CallableDefinition.
 * Generated by PHPUnit on 2013-06-28 at 00:09:38.
 */
class ArrayDefinitionTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ArrayDefinition
     */
    protected $object;

    public function setUp()
    {
        $me = $this;
        $this->object = new ArrayDefinition(array(
            'testArg'   => 'normalString',
            'property'  => ':propTest',
            'reference'  => '@testRef'
        ));
    }
    
    protected function getContainer()
    {
        $container = new Container();
        $container->set('testRef', 'testReferenceOk');
        $container->setProperty('propTest', 'testPropertyOk');
        
        return $container;
    }
    
    public function testArrayResultIsComplete()
    {
        $array = $this->object->invoke($this->getContainer());
        $this->assertTrue(is_array($array));
        $this->assertArrayHasKey('property', $array);
        $this->assertArrayHasKey('reference', $array);
        $this->assertArrayHasKey('testArg', $array);
        
        $this->assertEquals('testPropertyOk', $array['property']);
        $this->assertEquals('testReferenceOk', $array['reference']);
        $this->assertEquals('normalString', $array['testArg']);
    }
    
    public function testGettersAndSetters()
    {
        $arr = $this->object->getArray();
        $this->assertEquals($arr, $this->object->getArray());
        $arr['newProp'] = "ohyeah";
        $this->assertNotEquals($arr, $this->object->getArray());
        $this->object->setArray($arr);
        $this->assertEquals($arr, $this->object->getArray());
    }
}